% Lisp Syntax form of PR2D-DEMO.RED
%  2D Version

(LOAD PRLISP2D)
% Initialize for HP2648
(HP!.INIT)

% Build some ObJects

(SETQ OUTLINE 
      (POINTSET (ONEPOINT 10 10) (ONEPOINT -10 10) (ONEPOINT -10 -10) 
                (ONEPOINT 10 -10) (ONEPOINT 10 10)))
(SETQ ARROW 
      (GROUP (POINTSET (ONEPOINT 0 -1) (ONEPOINT 0 2)) 
             (POINTSET (ONEPOINT -1 1) (ONEPOINT 0 2) (ONEPOINT 1 1))))

(SETQ CUBE (GROUP OUTLINE ARROW))
(SETQ BIGCUBE (TRANSFORM CUBE (SCALE 5)))
(ESHOW CUBE)
(SHOW (TRANSFORM CUBE (XMOVE 30)))
(SHOW BIGCUBE)
(ESHOW (TRANSFORM BIGCUBE (ZROT 30)))
(ESHOW (TRANSFORM (ONEPOINT 10 10) (CIRCLE 70)))
(SETQ CPTS 
      (POINTSET (ONEPOINT 0 0) (ONEPOINT 70 -60) (ONEPOINT 189 -69) 
                (ONEPOINT 206 33) (ONEPOINT 145 130) (ONEPOINT 48 130) 
                (ONEPOINT 0 84)))
(ESHOW (TRANSFORM (ONEPOINT 10 10) (CIRCLE 50)))
(ESHOW (GROUP CPTS (TRANSFORM CPTS (BEZIER))))
(ESHOW (GROUP CPTS (TRANSFORM CPTS (BSPLINE))))
(ESHOW (TRANSFORM (TRANSFORM (TRANSFORM CUBE (SCALE 2)) (XMOVE -240)) 
                  (REPEATED 5 (XMOVE 80))))
(ESHOW (TRANSFORM (ONEPOINT 0 0) (TEXT "ABC DEF")))
(ESHOW (TRANSFORM (TRANSFORM (TRANSFORM (ONEPOINT 5 5) (TEXT "123 456")) 
                             (ZROT 25))
                  (SCALE 2)))
(ESHOW (TRANSFORM (ONEPOINT 10 10) (TEXT "123")))
(SHOW (TRANSFORM (TRANSFORM (ONEPOINT 30 30) (TEXT "456")) (SCALE 3)))
