(load rlisp)
(dskin "patch.sl")
(copyd 'list-to-string 'list2string)
(load clcomp)
;(setq *install t)
;(setq *traceall t)
(dskin "un-rlisp.lsp")
(compile '(collect-spelling-and-comments-aux-aux))
(collect-spelling-and-comments "pi:read.red")
