% NEW-TIME.SL  Driver of PSL "spectral" tests
% After loading psl-timer.b, LAPIN  this file

(de test(x y)
  (prin2 x)
  (setq y (timeeval y))	
  (print y)
  (setq Cases!* (cons (cons x y) Cases!*))	
  0)

(de rtest(x y)
    (reclaim)
    (test x y))

(de printcases (fil)
	(wrs (open  fil 'output))
	(setq c (reverse Cases!*))
	(prin2t "(")
	(while (pairp c) (print (car c)) (setq c (cdr c)))
	(prin2t ")")
	(close (wrs NIL))
)
(TestSetup)
(setq Cases!* (cons (cons (versionname) (date)) NIL))
(prin2 '!")
(prin2  "PSL Spectral Tests,  ") (prin2 (versionname)) 
	(prin2 ",  ") (prin2 (date))
(prin2t '!")
(rtest "EmptyTest-10000		"  '(EmptyTest 10000))
(test "GEmptyTest-10000	"  '(SlowEmptyTest 10000))
(test "Cdr1Test-100		"  '(Cdr1Test 100))
(test "Cdr2Test-100		"  '(Cdr2Test 100))
(test "CddrTest-100		"  '(CddrTest 100))
(test "ListOnlyCdrTest1	"  '(ListOnlyCdrTest1))
(test "ListOnlyCddrTest1	"  '(ListOnlyCddrTest1))
(test "ListOnlyCdrTest2	"  '(ListOnlyCdrTest2))
(test "ListOnlyCddrTest2	"  '(ListOnlyCddrTest2))
(test "ReverseTest-10		"  '(ReverseTest 10))
(rtest "MyReverse1Test-10	"  '(MyReverse1Test 10))
(rtest "MyReverse2Test-10	"  '(MyReverse2Test 10))
(rtest "LengthTest-100		"  '(LengthTest 100))
(test "ArithmeticTest-10000	"  '(ArithmeticTest 10000))
(test "EvalTest-10000		"  '(EvalTest 10000))
(test "tak-18-12-6		"  '(topleveltak 18 12 6))
(test "gtak-18-12-6		"  '(toplevelgtak 18 12 6))
(test "gtsta-g0		"  '(gtsta 'g0))
(test "gtsta-g1		"  '(gtsta 'g1))


