% TIME-PSL.SL  Driver of PSL "spectral" tests
% After loading psl-timer.b, LAPIN  this file

(wrs (open "time-psl.out" 'output))
(prin2  "PSL Spectral Tests,  ") (prin2 (versionname)) 
	(prin2 ",  ") (prin2T (date))
(prin2t 
"---------------------------------------------------------------")
(TestSetup)
(progn	(reclaim)
	(prin2 "EmptyTest 10000		")
	(print (TimeEval '(EmptyTest 10000))) 0)
(progn (prin2 "SlowEmptyTest 10000	")
	(print (TimeEval '(SlowEmptyTest 10000))) 0)
(progn (prin2 "Cdr1Test 100		")
	(print (TimeEval '(Cdr1Test 100))) 0)
(progn (prin2 "Cdr2Test 100		")
	(print (TimeEval '(Cdr2Test 100))) 0)
(progn (prin2 "CddrTest 100		")
	(print (TimeEval '(CddrTest 100))) 0)
(progn (prin2 "ListOnlyCdrTest1	")
	(print (TimeEval '(ListOnlyCdrTest1))) 0)
(progn (prin2 "ListOnlyCddrTest1	")
	(print (TimeEval '(ListOnlyCddrTest1))) 0)
(progn (prin2 "ListOnlyCdrTest2	")
	(print (TimeEval '(ListOnlyCdrTest2))) 0)
(progn (prin2 "ListOnlyCddrTest2	")
	(print (TimeEval '(ListOnlyCddrTest2))) 0)
(progn (prin2 "ReverseTest 10		")
	(print (TimeEval '(ReverseTest 10))) 0)
(progn (reclaim)
	(prin2 "MyReverse1Test 10	")
	(print (TimeEval '(MyReverse1Test 10))) 0)
(progn (reclaim)
	(prin2 "MyReverse2Test 10	")
	(print (TimeEval '(MyReverse2Test 10))) 0)
(progn (reclaim)
	(prin2 "LengthTest 100		")
	(print (TimeEval '(LengthTest 100))) 0)
(progn (prin2 "ArithmeticTest 10000	")
	(print (TimeEval '(ArithmeticTest 10000))) 0)
(progn (prin2 "EvalTest 10000		")
	(print (TimeEval '(EvalTest 10000))) 0)
(progn (prin2 "tak 18 12 6		")
	(print (TimeEval '(topleveltak 18 12 6))) 0)
(progn (prin2 "gtak 18 12 6		")
	(print (TimeEval '(toplevelgtak 18 12 6))) 0)
(progn (prin2 "gtsta g0		")
	(print (TimeEval '(gtsta 'g0))) 0)
(progn (prin2 "gtsta g1		")
	(print (TimeEval '(gtsta 'g1))) 0)
(close (wrs NIL))
