                      Version 3.1 PSL Available

We have just installed the latest version of Utah's PSL (Portable
Standard LISP) system. This system is written almost entirely in
itself, and is compiled with an efficient optimizing LISP compiler,
with machine oriented extensions (called "SYSLISP"). The LISP itself
is based on Utah Standard LISP, with modernizations and extensions
derived from FranzLISP, Common-LISP, etc.  PSL currently runs on
DEC-20 under TOPS-20, VAX under UNIX, and a number of Motorola MC68000
systems.  Future implementations for VAX-VMS, CRAY-1, IBM-370 and extended
addressing TOPS-20 are envisioned or already underway.

In order to run PSL, you must use a set of logical names, defined
in  <name>MINIMAL-LOGICAL-NAMES.CMD. You should insert a @TAKE of this
file in your LOGIN.CMD file.

A printed copy of the preliminary PSL manual can be obtained from
[........]; there is also a complete online version of this manual,
organized as a set of files, one per chapter. These are stored as
PLPT:nnnn-chaptername.LPT. PLEASE DO NOT print your own copy.

There are a set of short HELP files, on directory PH:. To get started,
read PH:PSL-INTRO.HLP.


The licence agrrement under which we have recieved this version of PSL
restricts it to our internal use. Please do not distribute the code (source
or listings), or documentation outside of our group.

If there are any problems, please MAIL to [.....].
