	search monsym
	radix 10
	extern STACK
	extern L0001
	extern L0002
	extern HEAP
	extern L0006
	extern L0007
	extern L0008
	extern L0009
	extern L0010
	extern L0011
	extern L0012
	extern BPS
	extern L0013
	extern L0014
	extern L0015
	extern L0016
;     (!*ENTRY INITHEAP EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (WVAR HEAPLOWERBOUND) (WVAR HEAPLAST))
;          (MOVE (REG T1) (WVAR HEAPLOWERBOUND))
;          (MOVEM (REG T1) (WVAR HEAPLAST))
;     (!*MOVE (WCONST 0) (REG 1))
;          (SETZM (REG 1))
;     (!*MOVE (REG 1) (WVAR HEAPPREVIOUSLAST))
;          (MOVEM (REG 1) (WVAR HEAPPREVIOUSLAST))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
	0
; (!*ENTRY INITHEAP EXPR 0)
L0017:	intern L0017
 MOVE 6,L0006
 MOVEM 6,L0008
 SETZM 1
 MOVEM 1,L0010
 POPJ 15,0
	extern L0004
	extern ARG1
	extern ARG2
	extern ARG3
	extern ARG4
	extern ARG5
	extern ARG6
	extern ARG7
	extern ARG8
	extern ARG9
	extern ARG10
	extern ARG11
	extern ARG12
	extern ARG13
	extern ARG14
	extern ARG15
	extern L0005
;     (!*ENTRY MAIN!. EXPR 0)
;          (RESET)
;          (MOVE (REG ST) (LIT (HALFWORD (MINUS (WCONST STACKSIZE)) (DIFFERENCE (WCONST STACK) 1))))
;          (MOVE (REG NIL) (FLUID NIL))
;     (!*LINKE 0 FIRSTCALL EXPR 0)
;          (HRRZI (REG LINKREG) 130)
;          (SETZM (REG NARGREG))
;          (JRST (ENTRY FIRSTCALL))
;          (HALFWORD (MINUS (WCONST STACKSIZE)) (DIFFERENCE (WCONST STACK) 1))
	0
; (!*ENTRY MAIN!. EXPR 0)
	intern MAIN.
MAIN.: RESET
 MOVE 15,L0018
 MOVE 0,SYMVAL+128
 HRRZI 12,130
 SETZM 13
 JRST SYMFNC+130
L0018:	byte(18)-5000,STACK-1
;     (!*ENTRY INIT EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (WCONST 0) (REG 1))
;          (SETZM (REG 1))
;     (!*LINK INIT20 EXPR 1)
	extern INIT20
;          (PUSHJ (REG ST) (INTERNALENTRY INIT20))
;     (!*MOVE (WCONST 0) (!$FLUID IN!*))
;          (SETZM (!$FLUID IN!*))
;     (!*MOVE (WCONST 1) (!$FLUID OUT!*))
;          (HRRZI (REG T1) 1)
;          (MOVEM (REG T1) (!$FLUID OUT!*))
;     (!*MOVE (QUOTE NIL) (REG 1))
;          (MOVE (REG 1) (REG NIL))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
	0
; (!*ENTRY INIT EXPR 0)
INIT:	intern INIT
 SETZM 1
 PUSHJ 15,INIT20
 SETZM SYMVAL+133
 HRRZI 6,1
 MOVEM 6,SYMVAL+134
 MOVE 1,0
 POPJ 15,0
;     (!*ENTRY GETC EXPR 0)
;     (!*ALLOC 0)
;     (!*JUMPNOTEQ (LABEL G0004) (WCONST 0) (!$FLUID IN!*))
;          (SKIPE (!$FLUID IN!*))
;          (JRST (LABEL G0004))
;     (!*MOVE (WCONST 0) (REG 1))
;          (SETZM (REG 1))
;     (!*LINKE 0 GETC20 EXPR 1)
	extern GETC20
;          (PUSHJ (REG ST) (INTERNALENTRY GETC20))
;          (POPJ (REG ST) 0)
;     (!*LBL (LABEL G0004))
;     (!*MOVE (!$FLUID IN!*) (REG 1))
;          (MOVE (REG 1) (!$FLUID IN!*))
;     (!*LINKE 0 INDEPENDENTREADCHAR EXPR 1)
;          (HRRZI (REG LINKREG) 135)
;          (HRRZI (REG NARGREG) 1)
;          (JRST (ENTRY INDEPENDENTREADCHAR))
	0
; (!*ENTRY GETC EXPR 0)
GETC:	intern GETC
 SKIPE SYMVAL+133
 JRST L0019
 SETZM 1
 PUSHJ 15,GETC20
 POPJ 15,0
L0019: MOVE 1,SYMVAL+133
 HRRZI 12,135
 HRRZI 13,1
 JRST SYMFNC+135
;     (!*ENTRY TIMC EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (WCONST 0) (REG 1))
;          (SETZM (REG 1))
;     (!*LINKE 0 TIMC20 EXPR 1)
	extern TIMC20
;          (PUSHJ (REG ST) (INTERNALENTRY TIMC20))
;          (POPJ (REG ST) 0)
	0
; (!*ENTRY TIMC EXPR 0)
TIMC:	intern TIMC
 SETZM 1
 PUSHJ 15,TIMC20
 POPJ 15,0
;     (!*ENTRY PUTC EXPR 1)
;     (!*ALLOC 0)
;     (!*JUMPNOTEQ (LABEL G0004) (WCONST 1) (!$FLUID OUT!*))
;          (MOVE (REG T2) (!$FLUID OUT!*))
;          (CAIE (REG T2) 1)
;          (JRST (LABEL G0004))
;     (!*LINKE 0 PUTC20 EXPR 1)
	extern PUTC20
;          (PUSHJ (REG ST) (INTERNALENTRY PUTC20))
;          (POPJ (REG ST) 0)
;     (!*LBL (LABEL G0004))
;     (!*MOVE (REG 1) (REG 2))
;          (MOVE (REG 2) (REG 1))
;     (!*MOVE (!$FLUID OUT!*) (REG 1))
;          (MOVE (REG 1) (!$FLUID OUT!*))
;     (!*LINKE 0 INDEPENDENTWRITECHAR EXPR 2)
;          (HRRZI (REG LINKREG) 138)
;          (HRRZI (REG NARGREG) 2)
;          (JRST (ENTRY INDEPENDENTWRITECHAR))
	1
; (!*ENTRY PUTC EXPR 1)
PUTC:	intern PUTC
 MOVE 7,SYMVAL+134
 CAIE 7,1
 JRST L0020
 PUSHJ 15,PUTC20
 POPJ 15,0
L0020: MOVE 2,1
 MOVE 1,SYMVAL+134
 HRRZI 12,138
 HRRZI 13,2
 JRST SYMFNC+138
;     (!*ENTRY QUIT EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (WCONST 0) (REG 1))
;          (SETZM (REG 1))
;     (!*LINKE 0 QUIT20 EXPR 1)
	extern QUIT20
;          (PUSHJ (REG ST) (INTERNALENTRY QUIT20))
;          (POPJ (REG ST) 0)
	0
; (!*ENTRY QUIT EXPR 0)
QUIT:	intern QUIT
 SETZM 1
 PUSHJ 15,QUIT20
 POPJ 15,0
;     (!*ENTRY EXITLISP EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (WCONST 0) (REG 1))
;          (SETZM (REG 1))
;     (!*LINKE 0 QUIT20 EXPR 1)
;          (PUSHJ (REG ST) (INTERNALENTRY QUIT20))
;          (POPJ (REG ST) 0)
	0
; (!*ENTRY EXITLISP EXPR 0)
L0021:	intern L0021
 SETZM 1
 PUSHJ 15,QUIT20
 POPJ 15,0
;     (!*ENTRY RESET EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (QUOTE "Should RESET here, but will QUIT") (REG 1))
;          (MOVE (REG 1) (QUOTE "Should RESET here, but will QUIT"))
;     (!*LINK PRIN2T EXPR 1)
;          (HRRZI (REG LINKREG) 142)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PRIN2T))
;     (!*LINK QUIT EXPR 0)
;          (HRRZI (REG LINKREG) 140)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY QUIT))
;     (!*MOVE (QUOTE NIL) (REG 1))
;          (MOVE (REG 1) (REG NIL))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
L0023:	31
	byte(7)83,104,111,117,108,100,32,82,69,83,69,84,32,104,101,114,101,44,32,98,117,116,32,119,105,108,108,32,81,85,73,84,0
	0
; (!*ENTRY RESET EXPR 0)
RESET:	intern RESET
 MOVE 1,L0022
 HRRZI 12,142
 HRRZI 13,1
 PUSHJ 15,SYMFNC+142
 HRRZI 12,140
 SETZM 13
 PUSHJ 15,SYMFNC+140
 MOVE 1,0
 POPJ 15,0
L0022:	<4_31>+L0023
;     (!*ENTRY DATE EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (QUOTE "No-Date-Yet") (REG 1))
;          (MOVE (REG 1) (QUOTE "No-Date-Yet"))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
L0025:	10
	byte(7)78,111,45,68,97,116,101,45,89,101,116,0
	0
; (!*ENTRY DATE EXPR 0)
DATE:	intern DATE
 MOVE 1,L0024
 POPJ 15,0
L0024:	<4_31>+L0025
;     (!*ENTRY VERSIONNAME EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (QUOTE "DEC-20 test system") (REG 1))
;          (MOVE (REG 1) (QUOTE "DEC-20 test system"))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
L0027:	17
	byte(7)68,69,67,45,50,48,32,116,101,115,116,32,115,121,115,116,101,109,0
	0
; (!*ENTRY VERSIONNAME EXPR 0)
L0028:	intern L0028
 MOVE 1,L0026
 POPJ 15,0
L0026:	<4_31>+L0027
;     (!*ENTRY PUTINT EXPR 1)
;     (!*ALLOC 0)
;     (!*LINKE 0 PUTI20 EXPR 1)
	extern PUTI20
;          (PUSHJ (REG ST) (INTERNALENTRY PUTI20))
;          (POPJ (REG ST) 0)
	1
; (!*ENTRY PUTINT EXPR 1)
PUTINT:	intern PUTINT
 PUSHJ 15,PUTI20
 POPJ 15,0
;     (!*ENTRY !%STORE!-JCALL EXPR 2)
;     (!*ALLOC 0)
;     (!*WOR (REG 1) 23085449216)
;          (IOR (REG 1) 23085449216)
;     (!*MOVE (REG 1) (MEMORY (REG 2) (WCONST 0)))
;          (MOVEM (REG 1) (INDEXED (REG 2) 0))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
	2
; (!*ENTRY !%STORE!-JCALL EXPR 2)
L0029:	intern L0029
 IOR 1,[23085449216]
 MOVEM 1,0(2)
 POPJ 15,0
;     (!*ENTRY !%COPY!-FUNCTION!-CELL EXPR 2)
;     (!*ALLOC 0)
;     (!*MOVE (MEMORY (REG 1) (WCONST 0)) (MEMORY (REG 2) (WCONST 0)))
;          (MOVE (REG T1) (INDEXED (REG 1) 0))
;          (MOVEM (REG T1) (INDEXED (REG 2) 0))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
	2
; (!*ENTRY !%COPY!-FUNCTION!-CELL EXPR 2)
L0030:	intern L0030
 MOVE 6,0(1)
 MOVEM 6,0(2)
 POPJ 15,0
;     (!*ENTRY UNDEFINEDFUNCTION EXPR 0)
;     (!*MOVE (REG LINKREG) (FLUID UNDEFNCODE!*))
;          (MOVEM (REG LINKREG) (FLUID UNDEFNCODE!*))
;     (!*MOVE (REG NARGREG) (FLUID UNDEFNNARG!*))
;          (MOVEM (REG NARGREG) (FLUID UNDEFNNARG!*))
;     (!*JCALL UNDEFINEDFUNCTIONAUX)
;          (JRST (ENTRY UNDEFINEDFUNCTIONAUX))
	0
; (!*ENTRY UNDEFINEDFUNCTION EXPR 0)
L0031:	intern L0031
 MOVEM 12,SYMVAL+150
 MOVEM 13,SYMVAL+151
 JRST SYMFNC+152
;     (!*ENTRY LONGTIMES EXPR 2)
;     (!*ALLOC 0)
;     (!*WTIMES2 (REG 1) (REG 2))
;          (IMUL (REG 1) (REG 2))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
	2
; (!*ENTRY LONGTIMES EXPR 2)
L0032:	intern L0032
 IMUL 1,2
 POPJ 15,0
;     (!*ENTRY LONGDIV EXPR 2)
;     (!*ALLOC 0)
;     (!*LINKE 0 WQUOTIENT EXPR 2)
;          (HRRZI (REG LINKREG) 154)
;          (HRRZI (REG NARGREG) 2)
;          (IDIV (REG 1) (REG 2))
;          (POPJ (REG ST) 0)
	2
; (!*ENTRY LONGDIV EXPR 2)
L0033:	intern L0033
 HRRZI 12,154
 HRRZI 13,2
 IDIV 1,2
 POPJ 15,0
;     (!*ENTRY LONGREMAINDER EXPR 2)
;     (!*ALLOC 0)
;     (!*LINKE 0 WREMAINDER EXPR 2)
;          (HRRZI (REG LINKREG) 156)
;          (HRRZI (REG NARGREG) 2)
;          (IDIV (REG 1) (REG 2))
;          (MOVE (REG 1) (REG 2))
;          (POPJ (REG ST) 0)
	2
; (!*ENTRY LONGREMAINDER EXPR 2)
L0034:	intern L0034
 HRRZI 12,156
 HRRZI 13,2
 IDIV 1,2
 MOVE 1,2
 POPJ 15,0
;     (!*ENTRY FIRSTCALL EXPR 0)
;     (!*ALLOC 0)
;     (!*LINK INIT EXPR 0)
;          (HRRZI (REG LINKREG) 132)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY INIT))
;     (!*MOVE (QUOTE 65) (REG 1))
;          (HRRZI (REG 1) 65)
;     (!*LINK PUTC EXPR 1)
;          (HRRZI (REG LINKREG) 139)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PUTC))
;     (!*MOVE (QUOTE 66) (REG 1))
;          (HRRZI (REG 1) 66)
;     (!*LINK PUTC EXPR 1)
;          (HRRZI (REG LINKREG) 139)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PUTC))
;     (!*LINK TERPRI EXPR 0)
;          (HRRZI (REG LINKREG) 158)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TERPRI))
;     (!*MOVE (QUOTE 1) (REG 1))
;          (HRRZI (REG 1) 1)
;     (!*LINK PUTINT EXPR 1)
;          (HRRZI (REG LINKREG) 146)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PUTINT))
;     (!*LINK TERPRI EXPR 0)
;          (HRRZI (REG LINKREG) 158)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TERPRI))
;     (!*MOVE (QUOTE 2) (REG 1))
;          (HRRZI (REG 1) 2)
;     (!*LINK PUTINT EXPR 1)
;          (HRRZI (REG LINKREG) 146)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PUTINT))
;     (!*LINK TERPRI EXPR 0)
;          (HRRZI (REG LINKREG) 158)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TERPRI))
;     (!*LINK TIMC EXPR 0)
;          (HRRZI (REG LINKREG) 137)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TIMC))
;     (!*LINK PUTINT EXPR 1)
;          (HRRZI (REG LINKREG) 146)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PUTINT))
;     (!*LINK TERPRI EXPR 0)
;          (HRRZI (REG LINKREG) 158)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TERPRI))
;     (!*LINK TIMC EXPR 0)
;          (HRRZI (REG LINKREG) 137)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TIMC))
;     (!*LINK PUTINT EXPR 1)
;          (HRRZI (REG LINKREG) 146)
;          (HRRZI (REG NARGREG) 1)
;          (PUSHJ (REG ST) (ENTRY PUTINT))
;     (!*LINK TERPRI EXPR 0)
;          (HRRZI (REG LINKREG) 158)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY TERPRI))
;     (!*LINK QUIT EXPR 0)
;          (HRRZI (REG LINKREG) 140)
;          (SETZM (REG NARGREG))
;          (PUSHJ (REG ST) (ENTRY QUIT))
;     (!*MOVE (QUOTE NIL) (REG 1))
;          (MOVE (REG 1) (REG NIL))
;     (!*EXIT 0)
;          (POPJ (REG ST) 0)
	0
; (!*ENTRY FIRSTCALL EXPR 0)
L0035:	intern L0035
 HRRZI 12,132
 SETZM 13
 PUSHJ 15,SYMFNC+132
 HRRZI 1,65
 HRRZI 12,139
 HRRZI 13,1
 PUSHJ 15,SYMFNC+139
 HRRZI 1,66
 HRRZI 12,139
 HRRZI 13,1
 PUSHJ 15,SYMFNC+139
 HRRZI 12,158
 SETZM 13
 PUSHJ 15,SYMFNC+158
 HRRZI 1,1
 HRRZI 12,146
 HRRZI 13,1
 PUSHJ 15,SYMFNC+146
 HRRZI 12,158
 SETZM 13
 PUSHJ 15,SYMFNC+158
 HRRZI 1,2
 HRRZI 12,146
 HRRZI 13,1
 PUSHJ 15,SYMFNC+146
 HRRZI 12,158
 SETZM 13
 PUSHJ 15,SYMFNC+158
 HRRZI 12,137
 SETZM 13
 PUSHJ 15,SYMFNC+137
 HRRZI 12,146
 HRRZI 13,1
 PUSHJ 15,SYMFNC+146
 HRRZI 12,158
 SETZM 13
 PUSHJ 15,SYMFNC+158
 HRRZI 12,137
 SETZM 13
 PUSHJ 15,SYMFNC+137
 HRRZI 12,146
 HRRZI 13,1
 PUSHJ 15,SYMFNC+146
 HRRZI 12,158
 SETZM 13
 PUSHJ 15,SYMFNC+158
 HRRZI 12,140
 SETZM 13
 PUSHJ 15,SYMFNC+140
 MOVE 1,0
 POPJ 15,0
;     (!*ENTRY TERPRI EXPR 0)
;     (!*ALLOC 0)
;     (!*MOVE (QUOTE 10) (REG 1))
;          (HRRZI (REG 1) 10)
;     (!*LINKE 0 PUTC EXPR 1)
;          (HRRZI (REG LINKREG) 139)
;          (HRRZI (REG NARGREG) 1)
;          (JRST (ENTRY PUTC))
	0
; (!*ENTRY TERPRI EXPR 0)
TERPRI:	intern TERPRI
 HRRZI 1,10
 HRRZI 12,139
 HRRZI 13,1
 JRST SYMFNC+139
	0
; (!*ENTRY INITCODE EXPR 0)
L0036:	intern L0036
 MOVE 1,0
 POPJ 15,0
	extern SYMVAL
	extern SYMPRP
	extern SYMNAM
L0037:	0
	byte(7)0,0
	intern L0037
L0038:	0
	byte(7)1,0
	intern L0038
L0039:	0
	byte(7)2,0
	intern L0039
L0040:	0
	byte(7)3,0
	intern L0040
L0041:	0
	byte(7)4,0
	intern L0041
L0042:	0
	byte(7)5,0
	intern L0042
L0043:	0
	byte(7)6,0
	intern L0043
L0044:	0
	byte(7)7,0
	intern L0044
L0045:	0
	byte(7)8,0
	intern L0045
L0046:	0
	byte(7)9,0
	intern L0046
L0047:	0
	byte(7)10,0
	intern L0047
L0048:	0
	byte(7)11,0
	intern L0048
L0049:	0
	byte(7)12,0
	intern L0049
L0050:	0
	byte(7)13,0
	intern L0050
L0051:	0
	byte(7)14,0
	intern L0051
L0052:	0
	byte(7)15,0
	intern L0052
L0053:	0
	byte(7)16,0
	intern L0053
L0054:	0
	byte(7)17,0
	intern L0054
L0055:	0
	byte(7)18,0
	intern L0055
L0056:	0
	byte(7)19,0
	intern L0056
L0057:	0
	byte(7)20,0
	intern L0057
L0058:	0
	byte(7)21,0
	intern L0058
L0059:	0
	byte(7)22,0
	intern L0059
L0060:	0
	byte(7)23,0
	intern L0060
L0061:	0
	byte(7)24,0
	intern L0061
L0062:	0
	byte(7)25,0
	intern L0062
L0063:	0
	byte(7)26,0
	intern L0063
L0064:	0
	byte(7)27,0
	intern L0064
L0065:	0
	byte(7)28,0
	intern L0065
L0066:	0
	byte(7)29,0
	intern L0066
L0067:	0
	byte(7)30,0
	intern L0067
L0068:	0
	byte(7)31,0
	intern L0068
L0069:	0
	byte(7)32,0
	intern L0069
L0070:	0
	byte(7)33,0
	intern L0070
L0071:	0
	byte(7)34,0
	intern L0071
L0072:	0
	byte(7)35,0
	intern L0072
L0073:	0
	byte(7)36,0
	intern L0073
L0074:	0
	byte(7)37,0
	intern L0074
L0075:	0
	byte(7)38,0
	intern L0075
L0076:	0
	byte(7)39,0
	intern L0076
L0077:	0
	byte(7)40,0
	intern L0077
L0078:	0
	byte(7)41,0
	intern L0078
L0079:	0
	byte(7)42,0
	intern L0079
L0080:	0
	byte(7)43,0
	intern L0080
L0081:	0
	byte(7)44,0
	intern L0081
L0082:	0
	byte(7)45,0
	intern L0082
L0083:	0
	byte(7)46,0
	intern L0083
L0084:	0
	byte(7)47,0
	intern L0084
L0085:	0
	byte(7)48,0
	intern L0085
L0086:	0
	byte(7)49,0
	intern L0086
L0087:	0
	byte(7)50,0
	intern L0087
L0088:	0
	byte(7)51,0
	intern L0088
L0089:	0
	byte(7)52,0
	intern L0089
L0090:	0
	byte(7)53,0
	intern L0090
L0091:	0
	byte(7)54,0
	intern L0091
L0092:	0
	byte(7)55,0
	intern L0092
L0093:	0
	byte(7)56,0
	intern L0093
L0094:	0
	byte(7)57,0
	intern L0094
L0095:	0
	byte(7)58,0
	intern L0095
L0096:	0
	byte(7)59,0
	intern L0096
L0097:	0
	byte(7)60,0
	intern L0097
L0098:	0
	byte(7)61,0
	intern L0098
L0099:	0
	byte(7)62,0
	intern L0099
L0100:	0
	byte(7)63,0
	intern L0100
L0101:	0
	byte(7)64,0
	intern L0101
L0102:	0
	byte(7)65,0
	intern L0102
L0103:	0
	byte(7)66,0
	intern L0103
L0104:	0
	byte(7)67,0
	intern L0104
L0105:	0
	byte(7)68,0
	intern L0105
L0106:	0
	byte(7)69,0
	intern L0106
L0107:	0
	byte(7)70,0
	intern L0107
L0108:	0
	byte(7)71,0
	intern L0108
L0109:	0
	byte(7)72,0
	intern L0109
L0110:	0
	byte(7)73,0
	intern L0110
L0111:	0
	byte(7)74,0
	intern L0111
L0112:	0
	byte(7)75,0
	intern L0112
L0113:	0
	byte(7)76,0
	intern L0113
L0114:	0
	byte(7)77,0
	intern L0114
L0115:	0
	byte(7)78,0
	intern L0115
L0116:	0
	byte(7)79,0
	intern L0116
L0117:	0
	byte(7)80,0
	intern L0117
L0118:	0
	byte(7)81,0
	intern L0118
L0119:	0
	byte(7)82,0
	intern L0119
L0120:	0
	byte(7)83,0
	intern L0120
L0121:	0
	byte(7)84,0
	intern L0121
L0122:	0
	byte(7)85,0
	intern L0122
L0123:	0
	byte(7)86,0
	intern L0123
L0124:	0
	byte(7)87,0
	intern L0124
L0125:	0
	byte(7)88,0
	intern L0125
L0126:	0
	byte(7)89,0
	intern L0126
L0127:	0
	byte(7)90,0
	intern L0127
L0128:	0
	byte(7)91,0
	intern L0128
L0129:	0
	byte(7)92,0
	intern L0129
L0130:	0
	byte(7)93,0
	intern L0130
L0131:	0
	byte(7)94,0
	intern L0131
L0132:	0
	byte(7)95,0
	intern L0132
L0133:	0
	byte(7)96,0
	intern L0133
L0134:	0
	byte(7)97,0
	intern L0134
L0135:	0
	byte(7)98,0
	intern L0135
L0136:	0
	byte(7)99,0
	intern L0136
L0137:	0
	byte(7)100,0
	intern L0137
L0138:	0
	byte(7)101,0
	intern L0138
L0139:	0
	byte(7)102,0
	intern L0139
L0140:	0
	byte(7)103,0
	intern L0140
L0141:	0
	byte(7)104,0
	intern L0141
L0142:	0
	byte(7)105,0
	intern L0142
L0143:	0
	byte(7)106,0
	intern L0143
L0144:	0
	byte(7)107,0
	intern L0144
L0145:	0
	byte(7)108,0
	intern L0145
L0146:	0
	byte(7)109,0
	intern L0146
L0147:	0
	byte(7)110,0
	intern L0147
L0148:	0
	byte(7)111,0
	intern L0148
L0149:	0
	byte(7)112,0
	intern L0149
L0150:	0
	byte(7)113,0
	intern L0150
L0151:	0
	byte(7)114,0
	intern L0151
L0152:	0
	byte(7)115,0
	intern L0152
L0153:	0
	byte(7)116,0
	intern L0153
L0154:	0
	byte(7)117,0
	intern L0154
L0155:	0
	byte(7)118,0
	intern L0155
L0156:	0
	byte(7)119,0
	intern L0156
L0157:	0
	byte(7)120,0
	intern L0157
L0158:	0
	byte(7)121,0
	intern L0158
L0159:	0
	byte(7)122,0
	intern L0159
L0160:	0
	byte(7)123,0
	intern L0160
L0161:	0
	byte(7)124,0
	intern L0161
L0162:	0
	byte(7)125,0
	intern L0162
L0163:	0
	byte(7)126,0
	intern L0163
L0164:	0
	byte(7)127,0
	intern L0164
L0165:	2
	byte(7)78,73,76,0
	intern L0165
L0166:	7
	byte(7)73,78,73,84,72,69,65,80,0
	intern L0166
L0167:	8
	byte(7)70,73,82,83,84,67,65,76,76,0
	intern L0167
L0168:	4
	byte(7)77,65,73,78,46,0
	intern L0168
L0169:	3
	byte(7)73,78,73,84,0
	intern L0169
L0170:	2
	byte(7)73,78,42,0
	intern L0170
L0171:	3
	byte(7)79,85,84,42,0
	intern L0171
L0172:	18
	byte(7)73,78,68,69,80,69,78,68,69,78,84,82,69,65,68,67,72,65,82,0
	intern L0172
L0173:	3
	byte(7)71,69,84,67,0
	intern L0173
L0174:	3
	byte(7)84,73,77,67,0
	intern L0174
L0175:	19
	byte(7)73,78,68,69,80,69,78,68,69,78,84,87,82,73,84,69,67,72,65,82,0
	intern L0175
L0176:	3
	byte(7)80,85,84,67,0
	intern L0176
L0177:	3
	byte(7)81,85,73,84,0
	intern L0177
L0178:	7
	byte(7)69,88,73,84,76,73,83,80,0
	intern L0178
L0179:	5
	byte(7)80,82,73,78,50,84,0
	intern L0179
L0180:	4
	byte(7)82,69,83,69,84,0
	intern L0180
L0181:	3
	byte(7)68,65,84,69,0
	intern L0181
L0182:	10
	byte(7)86,69,82,83,73,79,78,78,65,77,69,0
	intern L0182
L0183:	5
	byte(7)80,85,84,73,78,84,0
	intern L0183
L0184:	11
	byte(7)37,83,84,79,82,69,45,74,67,65,76,76,0
	intern L0184
L0185:	18
	byte(7)37,67,79,80,89,45,70,85,78,67,84,73,79,78,45,67,69,76,76,0
	intern L0185
L0186:	16
	byte(7)85,78,68,69,70,73,78,69,68,70,85,78,67,84,73,79,78,0
	intern L0186
L0187:	10
	byte(7)85,78,68,69,70,78,67,79,68,69,42,0
	intern L0187
L0188:	10
	byte(7)85,78,68,69,70,78,78,65,82,71,42,0
	intern L0188
L0189:	19
	byte(7)85,78,68,69,70,73,78,69,68,70,85,78,67,84,73,79,78,65,85,88,0
	intern L0189
L0190:	8
	byte(7)76,79,78,71,84,73,77,69,83,0
	intern L0190
L0191:	8
	byte(7)87,81,85,79,84,73,69,78,84,0
	intern L0191
L0192:	6
	byte(7)76,79,78,71,68,73,86,0
	intern L0192
L0193:	9
	byte(7)87,82,69,77,65,73,78,68,69,82,0
	intern L0193
L0194:	12
	byte(7)76,79,78,71,82,69,77,65,73,78,68,69,82,0
	intern L0194
L0195:	5
	byte(7)84,69,82,80,82,73,0
	intern L0195
L0196:	7
	byte(7)73,78,73,84,67,79,68,69,0
	intern L0196
	extern SYMFNC
	extern L0003
	end MAIN.
