% WINDOW.SL         28 Feb 83
% {DSK}WINDOW.PSL;1  5-FEB-83 15:51:00 





% GSN  2-FEB-83 13:57 
(DG WINDOW-CENTEROFFSET (W:WINDOW V:VECTOR)
(SEND W:REGION CENTEROFFSET V))


% GSN 13-JAN-83 16:28 
(DG WINDOW-DRAWLINE (W:WINDOW FROM:VECTOR TO:VECTOR)
(DRAWLINE FROM:X FROM:Y TO:X TO:Y 1 'PAINT
	  W))


% GSN 13-JAN-83 15:29 
(DG WINDOW-MOVETO (W:WINDOW POS:VECTOR)
(MOVETO POS:X POS:Y W))


% GSN 13-JAN-83 16:25 
(DG WINDOW-PRINTAT (W:WINDOW S:STRING POS:VECTOR)
(PROG (LASTWOP)
      (SEND W MOVETO POS)
      (SETQ LASTWOP (DSPOPERATION 'PAINT
				  W))
      (PRIN1 S W)
      (DSPOPERATION LASTWOP W)))


% GSN 13-JAN-83 16:28 
(DG WINDOW-UNDRAWLINE (W:WINDOW FROM:VECTOR TO:VECTOR)
(DRAWLINE FROM:X FROM:Y TO:X TO:Y 1 'ERASE
	  W))


% GSN 13-JAN-83 16:24 
(DG WINDOW-UNPRINTAT (W:WINDOW S:STRING POS:VECTOR)
(PROG (LASTWOP)
      (SEND W MOVETO POS)
      (SETQ LASTWOP (DSPOPERATION 'ERASE
				  W))
      (PRIN1 S W)
      (DSPOPERATION LASTWOP W)))


(GLISPOBJECTS


(WINDOW ANYTHING
PROP    ((REGION ((DSPCLIPPINGREGION NIL self))
		 RESULT DOLPHINREGION)
	 (XPOSITION ((DSPXPOSITION NIL self))
		    RESULT INTEGER)
	 (YPOSITION ((DSPYPOSITION NIL self))
		    RESULT INTEGER)
	 (HEIGHT (REGION:HEIGHT))
	 (WIDTH (REGION:WIDTH))
	 (LEFT ((DSPXOFFSET NIL self))
	       RESULT INTEGER)
	 (BOTTOM ((DSPYOFFSET NIL self))
		 RESULT INTEGER)
         (START (REGION:START))
         (SIZE  (REGION:SIZE)))
MSG     ((CLEAR CLEARW)
	 (OPEN OPENW)
	 (CLOSE CLOSEW)))

)

